// Copyright (C) 2026 Thorben Stangenberg
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program. If not, see <http://www.gnu.org/licenses/>.
//
// SPDX-License-Identifier: AGPL-3.0-or-later

package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const fileHeader = `<!-- Code generated by cmd/configdocs. DO NOT EDIT. -->
<!-- Regenerate: go run ./cmd/configdocs (from the module root) -->

# Configuration Reference

| Variable | Default | Description |
|----------|---------|-------------|
`

type envVar struct {
	Name        string
	Default     string
	Description string
}

func main() {
	if err := run(".", "docs/configuration.md"); err != nil {
		fmt.Fprintf(os.Stderr, "configdocs: %v\n", err)
		os.Exit(1)
	}
}

func run(root, out string) error {
	vars, err := collect(root)
	if err != nil {
		return err
	}
	sort.Slice(vars, func(i, j int) bool { return vars[i].Name < vars[j].Name })

	var buf bytes.Buffer
	buf.WriteString(fileHeader)
	for _, v := range vars {
		fmt.Fprintf(&buf, "| `%s` | %s | %s |\n", v.Name, v.Default, v.Description)
	}

	if err := os.WriteFile(out, buf.Bytes(), 0644); err != nil {
		return fmt.Errorf("write %s: %w", out, err)
	}
	fmt.Printf("wrote %s (%d variables)\n", out, len(vars))
	return nil
}

func collect(root string) ([]envVar, error) {
	var vars []envVar
	fset := token.NewFileSet()

	err := filepath.WalkDir(root, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			base := d.Name()
			if base == "vendor" || base == "testdata" || (strings.HasPrefix(base, ".") && base != ".") {
				return filepath.SkipDir
			}
			return nil
		}
		if !strings.HasSuffix(path, ".go") || strings.HasSuffix(path, "_test.go") {
			return nil
		}
		f, err := parser.ParseFile(fset, path, nil, parser.ParseComments)
		if err != nil {
			return fmt.Errorf("parse %s: %w", path, err)
		}
		for _, decl := range f.Decls {
			gd, ok := decl.(*ast.GenDecl)
			if !ok || gd.Tok != token.CONST {
				continue
			}
			for _, spec := range gd.Specs {
				vs, ok := spec.(*ast.ValueSpec)
				if !ok || len(vs.Names) == 0 || len(vs.Values) == 0 {
					continue
				}
				if !vs.Names[0].IsExported() {
					continue
				}
				lit, ok := vs.Values[0].(*ast.BasicLit)
				if !ok || lit.Kind != token.STRING {
					continue
				}
				val := strings.Trim(lit.Value, `"`)
				if !strings.HasPrefix(val, "STRATUM_") {
					continue
				}
				var commentText string
				if vs.Doc != nil {
					commentText = vs.Doc.Text()
				} else if gd.Doc != nil {
					commentText = gd.Doc.Text()
				}
				desc, def := parseComment(commentText)
				vars = append(vars, envVar{Name: val, Description: desc, Default: def})
			}
		}
		return nil
	})
	return vars, err
}

func parseComment(text string) (description, defaultVal string) {
	var descLines []string
	for _, line := range strings.Split(strings.TrimSpace(text), "\n") {
		line = strings.TrimSpace(line)
		if after, ok := strings.CutPrefix(line, "Default:"); ok {
			defaultVal = strings.TrimSpace(after)
		} else if line != "" {
			descLines = append(descLines, line)
		}
	}
	if defaultVal == "" {
		defaultVal = "none"
	}
	return strings.Join(descLines, " "), defaultVal
}
