//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/oapi-codegen/runtime"
)

const (
	ApiKeyAuthScopes apiKeyAuthContextKey = "ApiKeyAuth.Scopes"
)

// Defines values for ComponentHealthStatus.
const (
	ComponentHealthStatusError ComponentHealthStatus = "error"
	ComponentHealthStatusOk    ComponentHealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the ComponentHealthStatus enum.
func (e ComponentHealthStatus) Valid() bool {
	switch e {
	case ComponentHealthStatusError:
		return true
	case ComponentHealthStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for LivenessResponseStatus.
const (
	LivenessResponseStatusOk LivenessResponseStatus = "ok"
)

// Valid indicates whether the value is a known member of the LivenessResponseStatus enum.
func (e LivenessResponseStatus) Valid() bool {
	switch e {
	case LivenessResponseStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for ReadinessResponseStatus.
const (
	Degraded ReadinessResponseStatus = "degraded"
	Ok       ReadinessResponseStatus = "ok"
)

// Valid indicates whether the value is a known member of the ReadinessResponseStatus enum.
func (e ReadinessResponseStatus) Valid() bool {
	switch e {
	case Degraded:
		return true
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for SchemaChangeType.
const (
	FieldAdded   SchemaChangeType = "field_added"
	FieldRemoved SchemaChangeType = "field_removed"
	TypeAdded    SchemaChangeType = "type_added"
	TypeRemoved  SchemaChangeType = "type_removed"
)

// Valid indicates whether the value is a known member of the SchemaChangeType enum.
func (e SchemaChangeType) Valid() bool {
	switch e {
	case FieldAdded:
		return true
	case FieldRemoved:
		return true
	case TypeAdded:
		return true
	case TypeRemoved:
		return true
	default:
		return false
	}
}

// Defines values for SchemaStatusStatus.
const (
	SchemaStatusStatusError     SchemaStatusStatus = "error"
	SchemaStatusStatusMigrating SchemaStatusStatus = "migrating"
	SchemaStatusStatusReady     SchemaStatusStatus = "ready"
)

// Valid indicates whether the value is a known member of the SchemaStatusStatus enum.
func (e SchemaStatusStatus) Valid() bool {
	switch e {
	case SchemaStatusStatusError:
		return true
	case SchemaStatusStatusMigrating:
		return true
	case SchemaStatusStatusReady:
		return true
	default:
		return false
	}
}

// Defines values for SchemaUploadResponseStatus.
const (
	Applied SchemaUploadResponseStatus = "applied"
	Preview SchemaUploadResponseStatus = "preview"
)

// Valid indicates whether the value is a known member of the SchemaUploadResponseStatus enum.
func (e SchemaUploadResponseStatus) Valid() bool {
	switch e {
	case Applied:
		return true
	case Preview:
		return true
	default:
		return false
	}
}

// ComponentHealth defines model for ComponentHealth.
type ComponentHealth struct {
	// Details Optional extra info — must never contain credentials
	Details *map[string]interface{} `json:"details,omitempty"`
	Status  ComponentHealthStatus   `json:"status"`
}

// ComponentHealthStatus defines model for ComponentHealth.Status.
type ComponentHealthStatus string

// DeleteResult defines model for DeleteResult.
type DeleteResult struct {
	Success bool `json:"success"`
}

// Error defines model for Error.
type Error struct {
	Details *[]ErrorDetail `json:"details,omitempty"`
	Error   string         `json:"error"`
	Message string         `json:"message"`
}

// ErrorDetail defines model for ErrorDetail.
type ErrorDetail struct {
	Column  *int    `json:"column,omitempty"`
	Line    *int    `json:"line,omitempty"`
	Message *string `json:"message,omitempty"`
}

// InfoResponse defines model for InfoResponse.
type InfoResponse struct {
	BuiltAt *time.Time `json:"built_at,omitempty"`

	// Commit Git commit SHA
	Commit  *string `json:"commit,omitempty"`
	Version string  `json:"version"`
}

// LivenessResponse defines model for LivenessResponse.
type LivenessResponse struct {
	Status LivenessResponseStatus `json:"status"`
}

// LivenessResponseStatus defines model for LivenessResponse.Status.
type LivenessResponseStatus string

// ReadinessResponse defines model for ReadinessResponse.
type ReadinessResponse struct {
	Components map[string]ComponentHealth `json:"components"`
	Status     ReadinessResponseStatus    `json:"status"`
}

// ReadinessResponseStatus defines model for ReadinessResponse.Status.
type ReadinessResponseStatus string

// SchemaChange defines model for SchemaChange.
type SchemaChange struct {
	Destructive bool `json:"destructive"`

	// Field Field name (for field-level changes)
	Field *string `json:"field,omitempty"`

	// FieldType GraphQL scalar type (for field_added)
	FieldType *string `json:"fieldType,omitempty"`

	// On Type name the change applies to
	On   string           `json:"on"`
	Type SchemaChangeType `json:"type"`
}

// SchemaChangeType defines model for SchemaChange.Type.
type SchemaChangeType string

// SchemaDetail defines model for SchemaDetail.
type SchemaDetail struct {
	CreatedAt       time.Time `json:"created_at"`
	Description     *string   `json:"description,omitempty"`
	GraphqlEndpoint string    `json:"graphql_endpoint"`
	Name            string    `json:"name"`
	Sdl             string    `json:"sdl"`
	UpdatedAt       time.Time `json:"updated_at"`
	Version         int       `json:"version"`
}

// SchemaList defines model for SchemaList.
type SchemaList struct {
	Schemas []SchemaSummary `json:"schemas"`
}

// SchemaStatus defines model for SchemaStatus.
type SchemaStatus struct {
	Name      string             `json:"name"`
	Status    SchemaStatusStatus `json:"status"`
	UpdatedAt time.Time          `json:"updated_at"`
	Version   int                `json:"version"`
}

// SchemaStatusStatus defines model for SchemaStatus.Status.
type SchemaStatusStatus string

// SchemaSummary defines model for SchemaSummary.
type SchemaSummary struct {
	Name      string    `json:"name"`
	UpdatedAt time.Time `json:"updated_at"`
	Version   int       `json:"version"`
}

// SchemaUploadRequest defines model for SchemaUploadRequest.
type SchemaUploadRequest struct {
	// Changelog Comment describing this change (like a commit message)
	Changelog *string `json:"changelog,omitempty"`

	// Description Human-readable description of the schema
	Description *string `json:"description,omitempty"`

	// Sdl GraphQL SDL defining the domain model
	Sdl string `json:"sdl"`
}

// SchemaUploadResponse defines model for SchemaUploadResponse.
type SchemaUploadResponse struct {
	// Changes Present in preview mode — list of schema changes
	Changes         *[]SchemaChange `json:"changes,omitempty"`
	GraphqlEndpoint *string         `json:"graphql_endpoint,omitempty"`

	// IsDestructive Present in preview mode — true if any change would cause data loss
	IsDestructive *bool                      `json:"is_destructive,omitempty"`
	Name          string                     `json:"name"`
	Status        SchemaUploadResponseStatus `json:"status"`
	UpdatedAt     time.Time                  `json:"updated_at"`
	Version       int                        `json:"version"`
}

// SchemaUploadResponseStatus defines model for SchemaUploadResponse.Status.
type SchemaUploadResponseStatus string

// SchemaName defines model for SchemaName.
type SchemaName = string

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Conflict defines model for Conflict.
type Conflict = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// ValidationError defines model for ValidationError.
type ValidationError = Error

// apiKeyAuthContextKey is the context key for ApiKeyAuth security scheme
type apiKeyAuthContextKey string

// UpsertSchemaParams defines parameters for UpsertSchema.
type UpsertSchemaParams struct {
	// Preview If true, return a preview of changes without applying them
	Preview *bool `form:"preview,omitempty" json:"preview,omitempty"`
}

// UpsertSchemaJSONRequestBody defines body for UpsertSchema for application/json ContentType.
type UpsertSchemaJSONRequestBody = SchemaUploadRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Liveness check — is the process alive?
	// (GET /api/v1/health/live)
	Liveness(w http.ResponseWriter, r *http.Request)
	// Readiness check — are all dependencies healthy?
	// (GET /api/v1/health/ready)
	Readiness(w http.ResponseWriter, r *http.Request)
	// Stratum version and build information
	// (GET /api/v1/info)
	Info(w http.ResponseWriter, r *http.Request)
	// List all schemas
	// (GET /api/v1/schemas)
	ListSchemas(w http.ResponseWriter, r *http.Request)
	// Delete a schema and its tables
	// (DELETE /api/v1/schemas/{name})
	DeleteSchema(w http.ResponseWriter, r *http.Request, name SchemaName)
	// Get a schema
	// (GET /api/v1/schemas/{name})
	GetSchema(w http.ResponseWriter, r *http.Request, name SchemaName)
	// Create or update a schema (upsert)
	// (POST /api/v1/schemas/{name})
	UpsertSchema(w http.ResponseWriter, r *http.Request, name SchemaName, params UpsertSchemaParams)
	// Get schema status and version
	// (GET /api/v1/schemas/{name}/status)
	GetSchemaStatus(w http.ResponseWriter, r *http.Request, name SchemaName)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// Liveness operation middleware
func (siw *ServerInterfaceWrapper) Liveness(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Liveness(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Readiness operation middleware
func (siw *ServerInterfaceWrapper) Readiness(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Readiness(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Info operation middleware
func (siw *ServerInterfaceWrapper) Info(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Info(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListSchemas operation middleware
func (siw *ServerInterfaceWrapper) ListSchemas(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListSchemas(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteSchema operation middleware
func (siw *ServerInterfaceWrapper) DeleteSchema(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "name" -------------
	var name SchemaName

	err = runtime.BindStyledParameterWithOptions("simple", "name", r.PathValue("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteSchema(w, r, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSchema operation middleware
func (siw *ServerInterfaceWrapper) GetSchema(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "name" -------------
	var name SchemaName

	err = runtime.BindStyledParameterWithOptions("simple", "name", r.PathValue("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSchema(w, r, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpsertSchema operation middleware
func (siw *ServerInterfaceWrapper) UpsertSchema(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "name" -------------
	var name SchemaName

	err = runtime.BindStyledParameterWithOptions("simple", "name", r.PathValue("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params UpsertSchemaParams

	// ------------- Optional query parameter "preview" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "preview", r.URL.Query(), &params.Preview, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "preview"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "preview", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpsertSchema(w, r, name, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSchemaStatus operation middleware
func (siw *ServerInterfaceWrapper) GetSchemaStatus(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "name" -------------
	var name SchemaName

	err = runtime.BindStyledParameterWithOptions("simple", "name", r.PathValue("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSchemaStatus(w, r, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/health/live", wrapper.Liveness)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/health/ready", wrapper.Readiness)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/info", wrapper.Info)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/schemas", wrapper.ListSchemas)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/api/v1/schemas/{name}", wrapper.DeleteSchema)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/schemas/{name}", wrapper.GetSchema)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/schemas/{name}", wrapper.UpsertSchema)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/schemas/{name}/status", wrapper.GetSchemaStatus)

	return m
}

type BadRequestJSONResponse Error

type ConflictJSONResponse Error

type NotFoundJSONResponse Error

type UnauthorizedJSONResponse Error

type ValidationErrorJSONResponse Error

type LivenessRequestObject struct {
}

type LivenessResponseObject interface {
	VisitLivenessResponse(w http.ResponseWriter) error
}

type Liveness200JSONResponse LivenessResponse

func (response Liveness200JSONResponse) VisitLivenessResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ReadinessRequestObject struct {
}

type ReadinessResponseObject interface {
	VisitReadinessResponse(w http.ResponseWriter) error
}

type Readiness200JSONResponse ReadinessResponse

func (response Readiness200JSONResponse) VisitReadinessResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type Readiness503JSONResponse ReadinessResponse

func (response Readiness503JSONResponse) VisitReadinessResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type InfoRequestObject struct {
}

type InfoResponseObject interface {
	VisitInfoResponse(w http.ResponseWriter) error
}

type Info200JSONResponse InfoResponse

func (response Info200JSONResponse) VisitInfoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListSchemasRequestObject struct {
}

type ListSchemasResponseObject interface {
	VisitListSchemasResponse(w http.ResponseWriter) error
}

type ListSchemas200JSONResponse SchemaList

func (response ListSchemas200JSONResponse) VisitListSchemasResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListSchemas401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListSchemas401JSONResponse) VisitListSchemasResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteSchemaRequestObject struct {
	Name SchemaName `json:"name"`
}

type DeleteSchemaResponseObject interface {
	VisitDeleteSchemaResponse(w http.ResponseWriter) error
}

type DeleteSchema200JSONResponse DeleteResult

func (response DeleteSchema200JSONResponse) VisitDeleteSchemaResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteSchema401JSONResponse struct{ UnauthorizedJSONResponse }

func (response DeleteSchema401JSONResponse) VisitDeleteSchemaResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteSchema404JSONResponse struct{ NotFoundJSONResponse }

func (response DeleteSchema404JSONResponse) VisitDeleteSchemaResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetSchemaRequestObject struct {
	Name SchemaName `json:"name"`
}

type GetSchemaResponseObject interface {
	VisitGetSchemaResponse(w http.ResponseWriter) error
}

type GetSchema200JSONResponse SchemaDetail

func (response GetSchema200JSONResponse) VisitGetSchemaResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetSchema401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetSchema401JSONResponse) VisitGetSchemaResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetSchema404JSONResponse struct{ NotFoundJSONResponse }

func (response GetSchema404JSONResponse) VisitGetSchemaResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UpsertSchemaRequestObject struct {
	Name   SchemaName `json:"name"`
	Params UpsertSchemaParams
	Body   *UpsertSchemaJSONRequestBody
}

type UpsertSchemaResponseObject interface {
	VisitUpsertSchemaResponse(w http.ResponseWriter) error
}

type UpsertSchema200JSONResponse SchemaUploadResponse

func (response UpsertSchema200JSONResponse) VisitUpsertSchemaResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpsertSchema400JSONResponse struct{ BadRequestJSONResponse }

func (response UpsertSchema400JSONResponse) VisitUpsertSchemaResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type UpsertSchema401JSONResponse struct{ UnauthorizedJSONResponse }

func (response UpsertSchema401JSONResponse) VisitUpsertSchemaResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type UpsertSchema409JSONResponse struct{ ConflictJSONResponse }

func (response UpsertSchema409JSONResponse) VisitUpsertSchemaResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type UpsertSchema422JSONResponse struct{ ValidationErrorJSONResponse }

func (response UpsertSchema422JSONResponse) VisitUpsertSchemaResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type GetSchemaStatusRequestObject struct {
	Name SchemaName `json:"name"`
}

type GetSchemaStatusResponseObject interface {
	VisitGetSchemaStatusResponse(w http.ResponseWriter) error
}

type GetSchemaStatus200JSONResponse SchemaStatus

func (response GetSchemaStatus200JSONResponse) VisitGetSchemaStatusResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetSchemaStatus401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetSchemaStatus401JSONResponse) VisitGetSchemaStatusResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetSchemaStatus404JSONResponse struct{ NotFoundJSONResponse }

func (response GetSchemaStatus404JSONResponse) VisitGetSchemaStatusResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Liveness check — is the process alive?
	// (GET /api/v1/health/live)
	Liveness(ctx context.Context, request LivenessRequestObject) (LivenessResponseObject, error)
	// Readiness check — are all dependencies healthy?
	// (GET /api/v1/health/ready)
	Readiness(ctx context.Context, request ReadinessRequestObject) (ReadinessResponseObject, error)
	// Stratum version and build information
	// (GET /api/v1/info)
	Info(ctx context.Context, request InfoRequestObject) (InfoResponseObject, error)
	// List all schemas
	// (GET /api/v1/schemas)
	ListSchemas(ctx context.Context, request ListSchemasRequestObject) (ListSchemasResponseObject, error)
	// Delete a schema and its tables
	// (DELETE /api/v1/schemas/{name})
	DeleteSchema(ctx context.Context, request DeleteSchemaRequestObject) (DeleteSchemaResponseObject, error)
	// Get a schema
	// (GET /api/v1/schemas/{name})
	GetSchema(ctx context.Context, request GetSchemaRequestObject) (GetSchemaResponseObject, error)
	// Create or update a schema (upsert)
	// (POST /api/v1/schemas/{name})
	UpsertSchema(ctx context.Context, request UpsertSchemaRequestObject) (UpsertSchemaResponseObject, error)
	// Get schema status and version
	// (GET /api/v1/schemas/{name}/status)
	GetSchemaStatus(ctx context.Context, request GetSchemaStatusRequestObject) (GetSchemaStatusResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// Liveness operation middleware
func (sh *strictHandler) Liveness(w http.ResponseWriter, r *http.Request) {
	var request LivenessRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Liveness(ctx, request.(LivenessRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Liveness")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LivenessResponseObject); ok {
		if err := validResponse.VisitLivenessResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Readiness operation middleware
func (sh *strictHandler) Readiness(w http.ResponseWriter, r *http.Request) {
	var request ReadinessRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Readiness(ctx, request.(ReadinessRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Readiness")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ReadinessResponseObject); ok {
		if err := validResponse.VisitReadinessResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Info operation middleware
func (sh *strictHandler) Info(w http.ResponseWriter, r *http.Request) {
	var request InfoRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Info(ctx, request.(InfoRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Info")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(InfoResponseObject); ok {
		if err := validResponse.VisitInfoResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListSchemas operation middleware
func (sh *strictHandler) ListSchemas(w http.ResponseWriter, r *http.Request) {
	var request ListSchemasRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListSchemas(ctx, request.(ListSchemasRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListSchemas")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListSchemasResponseObject); ok {
		if err := validResponse.VisitListSchemasResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteSchema operation middleware
func (sh *strictHandler) DeleteSchema(w http.ResponseWriter, r *http.Request, name SchemaName) {
	var request DeleteSchemaRequestObject

	request.Name = name

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteSchema(ctx, request.(DeleteSchemaRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteSchema")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteSchemaResponseObject); ok {
		if err := validResponse.VisitDeleteSchemaResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetSchema operation middleware
func (sh *strictHandler) GetSchema(w http.ResponseWriter, r *http.Request, name SchemaName) {
	var request GetSchemaRequestObject

	request.Name = name

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetSchema(ctx, request.(GetSchemaRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSchema")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetSchemaResponseObject); ok {
		if err := validResponse.VisitGetSchemaResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpsertSchema operation middleware
func (sh *strictHandler) UpsertSchema(w http.ResponseWriter, r *http.Request, name SchemaName, params UpsertSchemaParams) {
	var request UpsertSchemaRequestObject

	request.Name = name
	request.Params = params

	var body UpsertSchemaJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpsertSchema(ctx, request.(UpsertSchemaRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpsertSchema")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpsertSchemaResponseObject); ok {
		if err := validResponse.VisitUpsertSchemaResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetSchemaStatus operation middleware
func (sh *strictHandler) GetSchemaStatus(w http.ResponseWriter, r *http.Request, name SchemaName) {
	var request GetSchemaStatusRequestObject

	request.Name = name

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetSchemaStatus(ctx, request.(GetSchemaStatusRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSchemaStatus")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetSchemaStatusResponseObject); ok {
		if err := validResponse.VisitGetSchemaStatusResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
