//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package api

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/oapi-codegen/runtime"
)

const (
	ApiKeyAuthScopes apiKeyAuthContextKey = "ApiKeyAuth.Scopes"
)

// Defines values for ComponentHealthStatus.
const (
	ComponentHealthStatusError ComponentHealthStatus = "error"
	ComponentHealthStatusOk    ComponentHealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the ComponentHealthStatus enum.
func (e ComponentHealthStatus) Valid() bool {
	switch e {
	case ComponentHealthStatusError:
		return true
	case ComponentHealthStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for LivenessResponseStatus.
const (
	LivenessResponseStatusOk LivenessResponseStatus = "ok"
)

// Valid indicates whether the value is a known member of the LivenessResponseStatus enum.
func (e LivenessResponseStatus) Valid() bool {
	switch e {
	case LivenessResponseStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for ReadinessResponseStatus.
const (
	Degraded ReadinessResponseStatus = "degraded"
	Ok       ReadinessResponseStatus = "ok"
)

// Valid indicates whether the value is a known member of the ReadinessResponseStatus enum.
func (e ReadinessResponseStatus) Valid() bool {
	switch e {
	case Degraded:
		return true
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for SchemaChangeType.
const (
	FieldAdded   SchemaChangeType = "field_added"
	FieldRemoved SchemaChangeType = "field_removed"
	TypeAdded    SchemaChangeType = "type_added"
	TypeRemoved  SchemaChangeType = "type_removed"
)

// Valid indicates whether the value is a known member of the SchemaChangeType enum.
func (e SchemaChangeType) Valid() bool {
	switch e {
	case FieldAdded:
		return true
	case FieldRemoved:
		return true
	case TypeAdded:
		return true
	case TypeRemoved:
		return true
	default:
		return false
	}
}

// Defines values for SchemaStatusStatus.
const (
	SchemaStatusStatusError     SchemaStatusStatus = "error"
	SchemaStatusStatusMigrating SchemaStatusStatus = "migrating"
	SchemaStatusStatusReady     SchemaStatusStatus = "ready"
)

// Valid indicates whether the value is a known member of the SchemaStatusStatus enum.
func (e SchemaStatusStatus) Valid() bool {
	switch e {
	case SchemaStatusStatusError:
		return true
	case SchemaStatusStatusMigrating:
		return true
	case SchemaStatusStatusReady:
		return true
	default:
		return false
	}
}

// Defines values for SchemaUploadResponseStatus.
const (
	Applied SchemaUploadResponseStatus = "applied"
	Preview SchemaUploadResponseStatus = "preview"
)

// Valid indicates whether the value is a known member of the SchemaUploadResponseStatus enum.
func (e SchemaUploadResponseStatus) Valid() bool {
	switch e {
	case Applied:
		return true
	case Preview:
		return true
	default:
		return false
	}
}

// ComponentHealth defines model for ComponentHealth.
type ComponentHealth struct {
	// Details Optional extra info — must never contain credentials
	Details *map[string]interface{} `json:"details,omitempty"`
	Status  ComponentHealthStatus   `json:"status"`
}

// ComponentHealthStatus defines model for ComponentHealth.Status.
type ComponentHealthStatus string

// DeleteResult defines model for DeleteResult.
type DeleteResult struct {
	Success bool `json:"success"`
}

// Error defines model for Error.
type Error struct {
	Details *[]ErrorDetail `json:"details,omitempty"`
	Error   string         `json:"error"`
	Message string         `json:"message"`
}

// ErrorDetail defines model for ErrorDetail.
type ErrorDetail struct {
	Column  *int    `json:"column,omitempty"`
	Line    *int    `json:"line,omitempty"`
	Message *string `json:"message,omitempty"`
}

// InfoResponse defines model for InfoResponse.
type InfoResponse struct {
	BuiltAt *time.Time `json:"built_at,omitempty"`

	// Commit Git commit SHA
	Commit  *string `json:"commit,omitempty"`
	Version string  `json:"version"`
}

// LivenessResponse defines model for LivenessResponse.
type LivenessResponse struct {
	Status LivenessResponseStatus `json:"status"`
}

// LivenessResponseStatus defines model for LivenessResponse.Status.
type LivenessResponseStatus string

// ReadinessResponse defines model for ReadinessResponse.
type ReadinessResponse struct {
	Components map[string]ComponentHealth `json:"components"`
	Status     ReadinessResponseStatus    `json:"status"`
}

// ReadinessResponseStatus defines model for ReadinessResponse.Status.
type ReadinessResponseStatus string

// SchemaChange defines model for SchemaChange.
type SchemaChange struct {
	Destructive bool `json:"destructive"`

	// Field Field name (for field-level changes)
	Field *string `json:"field,omitempty"`

	// FieldType GraphQL scalar type (for field_added)
	FieldType *string `json:"fieldType,omitempty"`

	// On Type name the change applies to
	On   string           `json:"on"`
	Type SchemaChangeType `json:"type"`
}

// SchemaChangeType defines model for SchemaChange.Type.
type SchemaChangeType string

// SchemaDetail defines model for SchemaDetail.
type SchemaDetail struct {
	CreatedAt       time.Time `json:"created_at"`
	Description     *string   `json:"description,omitempty"`
	GraphqlEndpoint string    `json:"graphql_endpoint"`
	Name            string    `json:"name"`
	Sdl             string    `json:"sdl"`
	UpdatedAt       time.Time `json:"updated_at"`
	Version         int       `json:"version"`
}

// SchemaList defines model for SchemaList.
type SchemaList struct {
	Schemas []SchemaSummary `json:"schemas"`
}

// SchemaStatus defines model for SchemaStatus.
type SchemaStatus struct {
	Name      string             `json:"name"`
	Status    SchemaStatusStatus `json:"status"`
	UpdatedAt time.Time          `json:"updated_at"`
	Version   int                `json:"version"`
}

// SchemaStatusStatus defines model for SchemaStatus.Status.
type SchemaStatusStatus string

// SchemaSummary defines model for SchemaSummary.
type SchemaSummary struct {
	Name      string    `json:"name"`
	UpdatedAt time.Time `json:"updated_at"`
	Version   int       `json:"version"`
}

// SchemaUploadRequest defines model for SchemaUploadRequest.
type SchemaUploadRequest struct {
	// Changelog Comment describing this change (like a commit message)
	Changelog *string `json:"changelog,omitempty"`

	// Description Human-readable description of the schema
	Description *string `json:"description,omitempty"`

	// Sdl GraphQL SDL defining the domain model
	Sdl string `json:"sdl"`
}

// SchemaUploadResponse defines model for SchemaUploadResponse.
type SchemaUploadResponse struct {
	// Changes Present in preview mode — list of schema changes
	Changes         *[]SchemaChange `json:"changes,omitempty"`
	GraphqlEndpoint *string         `json:"graphql_endpoint,omitempty"`

	// IsDestructive Present in preview mode — true if any change would cause data loss
	IsDestructive *bool                      `json:"is_destructive,omitempty"`
	Name          string                     `json:"name"`
	Status        SchemaUploadResponseStatus `json:"status"`
	UpdatedAt     time.Time                  `json:"updated_at"`
	Version       int                        `json:"version"`
}

// SchemaUploadResponseStatus defines model for SchemaUploadResponse.Status.
type SchemaUploadResponseStatus string

// SchemaName defines model for SchemaName.
type SchemaName = string

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Conflict defines model for Conflict.
type Conflict = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// ValidationError defines model for ValidationError.
type ValidationError = Error

// apiKeyAuthContextKey is the context key for ApiKeyAuth security scheme
type apiKeyAuthContextKey string

// UpsertSchemaParams defines parameters for UpsertSchema.
type UpsertSchemaParams struct {
	// Preview If true, return a preview of changes without applying them
	Preview *bool `form:"preview,omitempty" json:"preview,omitempty"`
}

// UpsertSchemaJSONRequestBody defines body for UpsertSchema for application/json ContentType.
type UpsertSchemaJSONRequestBody = SchemaUploadRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Liveness check — is the process alive?
	// (GET /api/v1/health/live)
	Liveness(w http.ResponseWriter, r *http.Request)
	// Readiness check — are all dependencies healthy?
	// (GET /api/v1/health/ready)
	Readiness(w http.ResponseWriter, r *http.Request)
	// Stratum version and build information
	// (GET /api/v1/info)
	Info(w http.ResponseWriter, r *http.Request)
	// List all schemas
	// (GET /api/v1/schemas)
	ListSchemas(w http.ResponseWriter, r *http.Request)
	// Delete a schema and its tables
	// (DELETE /api/v1/schemas/{name})
	DeleteSchema(w http.ResponseWriter, r *http.Request, name SchemaName)
	// Get a schema
	// (GET /api/v1/schemas/{name})
	GetSchema(w http.ResponseWriter, r *http.Request, name SchemaName)
	// Create or update a schema (upsert)
	// (POST /api/v1/schemas/{name})
	UpsertSchema(w http.ResponseWriter, r *http.Request, name SchemaName, params UpsertSchemaParams)
	// Get schema status and version
	// (GET /api/v1/schemas/{name}/status)
	GetSchemaStatus(w http.ResponseWriter, r *http.Request, name SchemaName)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// Liveness operation middleware
func (siw *ServerInterfaceWrapper) Liveness(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Liveness(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Readiness operation middleware
func (siw *ServerInterfaceWrapper) Readiness(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Readiness(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Info operation middleware
func (siw *ServerInterfaceWrapper) Info(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Info(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListSchemas operation middleware
func (siw *ServerInterfaceWrapper) ListSchemas(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListSchemas(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteSchema operation middleware
func (siw *ServerInterfaceWrapper) DeleteSchema(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "name" -------------
	var name SchemaName

	err = runtime.BindStyledParameterWithOptions("simple", "name", r.PathValue("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteSchema(w, r, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSchema operation middleware
func (siw *ServerInterfaceWrapper) GetSchema(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "name" -------------
	var name SchemaName

	err = runtime.BindStyledParameterWithOptions("simple", "name", r.PathValue("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSchema(w, r, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpsertSchema operation middleware
func (siw *ServerInterfaceWrapper) UpsertSchema(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "name" -------------
	var name SchemaName

	err = runtime.BindStyledParameterWithOptions("simple", "name", r.PathValue("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params UpsertSchemaParams

	// ------------- Optional query parameter "preview" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "preview", r.URL.Query(), &params.Preview, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "preview"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "preview", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpsertSchema(w, r, name, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSchemaStatus operation middleware
func (siw *ServerInterfaceWrapper) GetSchemaStatus(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "name" -------------
	var name SchemaName

	err = runtime.BindStyledParameterWithOptions("simple", "name", r.PathValue("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSchemaStatus(w, r, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/health/live", wrapper.Liveness)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/health/ready", wrapper.Readiness)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/info", wrapper.Info)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/schemas", wrapper.ListSchemas)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/api/v1/schemas/{name}", wrapper.DeleteSchema)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/schemas/{name}", wrapper.GetSchema)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/schemas/{name}", wrapper.UpsertSchema)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/schemas/{name}/status", wrapper.GetSchemaStatus)

	return m
}
